### ISSUE TITLE
Improve the exersice

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-marinarodriguez#1]
Really cool job @marinarodriguez !!!

Here you have some tips to improve the exercise:

- [x] Remove `script` tag.
- [x] Add an alternative text to the images.
- [x] On classes names separate word with a hyphen
- [x] Remove the extra divs around the header content and around the logo link.
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] To center the menu vertically on the tablet, remove the default margin of ul.
- [x] Avoid uppercase/capital on HTML texts, and `br` tags. We can transform the text with CSS, this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: center the words
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

Let me know if you have any doubts ;)

Go for it!!

**Comment by marinarodriguez** [comment]
@nasivuela It's ready to review!

**Comment by nasivuela** [comment]
Ey! There is a couple of points that still need some work

- Work on the indentation of the media queries
- `creando<br>diversidad<br>digital` would be better as `Creando diversidad digital`

**Comment by marinarodriguez** [comment]
@nasivuela Changes has been made, also made some minor improvements, it's ready to review!

**Comment by nasivuela** [comment]
Awesome @marinarodriguez !!!
Regarding indentation, if you leave an empty line between CSS rules it is easier to read and the content of media queries would be better indented ;)
I'm closing the issue because it looks great to me!!

![](https://media.giphy.com/media/ujmbr3Va4hMSex7Jui/giphy.gif)
